Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.provider :virtualbox do |v|
      v.memory = 2048
      v.cpus = 1
    end
  
    boxes = [
      { :name => "ipa.otus.lan",
        :ip => "192.168.57.10",
      },
      { :name => "client1.otus.lan",
        :ip => "192.168.57.11",
      },
      { :name => "client2.otus.lan",
        :ip => "192.168.57.12",
      }
    ]
    boxes.each do |opts|
      config.vm.define opts[:name] do |config|
        config.vm.hostname = opts[:name]
        config.vm.network "private_network", ip: opts[:ip]
      end
     config.vm.provision "ansible" do |ansible|
     	ansible.playbook = "book/playbook.yml"
     	ansible.inventory_path = "inventory/hosts"
     	ansible.become = "true"
      end
    end
  end

